name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      env:
          repo_name: ${{ github.repository }}
      - uses: actions/checkout@v3
      - run: echo repo_name
      - run: echo ${{github.repository}}
      - run: echo ${{ github.repository }}