name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - name: get github repo
        env:
          repo_name: ${{ github.repository }}
        run: echo repo_name
      - run: echo ${{github.repository}}
      - run: echo ${{ github.repository }}